### ISSUE TITLE
Ability to move preload to the top of <head>

### ISSUE THREAD

**Issue by kurtextrem** [numical/script-ext-html-webpack-plugin#25]
This is somewhat for perf geeks, but if the head is quite long (because lots of icon attrs and meta tags), it would be useful to have an option to add the preload tags right at the start of `<head>`.
That way the browser can preload earlier.

**Comment by numical** [comment]
Hi,
I will not be doing this for two good reasons:
1. I can't!  This plugin relies on the parent HtmlWebpackPlugin to actually insert the elements in the `<head>`.  Without major changes, I cannot specify where in the `<head>` these are put - see [this issue](https://github.com/numical/script-ext-html-webpack-plugin/issues/6) for much more discussion regarding this.
2. Due to [speculative parsing](https://www.html5rocks.com/en/tutorials/internals/howbrowserswork/#The_order_of_processing_scripts_and_style_sheets) changing the position of the preloads ought not make any difference.
